// <auto-generated />
using System;
using BibliotecaRosa.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BibliotecaRosa.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260525191446_CriarEstruturaFinal")]
    partial class CriarEstruturaFinal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BibliotecaRosa.Models.Livro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Isbn")
                        .IsUnique();

                    b.ToTable("Livros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Autor = "J.R.R. Tolkien",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Isbn = "9788533613379",
                            Titulo = "O Senhor dos Anéis"
                        });
                });

            modelBuilder.Entity("BibliotecaRosa.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@rosa.com",
                            Nome = "Admin Rosa",
                            Role = 1,
                            SenhaHash = "$2a$11$eImiTXuWV5M729BOn7gMvO8V8L09Fvsh1F3A.Z3rYdM5m1YmXoRFe"
                        },
                        new
                        {
                            Id = 2,
                            Email = "professor@rosa.com",
                            Nome = "Professor Girafales",
                            Role = 2,
                            SenhaHash = "$2a$11$eImiTXuWV5M729BOn7gMvO8V8L09Fvsh1F3A.Z3rYdM5m1YmXoRFe"
                        },
                        new
                        {
                            Id = 3,
                            Email = "aluno@rosa.com",
                            Nome = "Aluno Chaves",
                            Role = 3,
                            SenhaHash = "$2a$11$eImiTXuWV5M729BOn7gMvO8V8L09Fvsh1F3A.Z3rYdM5m1YmXoRFe"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
